### ISSUE TITLE
Implement Maven/Gradle

### ISSUE THREAD

**Issue by zeonin** [MSUTeam1/unbanner#21]
As a developer, I want my project to be easily built. To that end I want to use Maven/Gradle to have the project be easily built.

**Comment by cblanto7** [comment]
I will vote for Gradle

**Comment by toasterbrain** [comment]
gradle

**Comment by Brodski** [comment]
I'm slightly in favor gradle b/c I know android uses gradle, so learning gradle might be will be more valuable for the possibly of any sort of android app job. Also, Android Studio (the IDE used to make android apps) is built bassed off of IntelliJ, so I'd imagine it wont be too difficult to use gradle w/ InteliJ

There is also a tutorialspoint.com section for gradle and maven so I'm guessing they would be equally difficult to learn.

 I'm sure maven is just as great, but I dont know anything about maven ,which is why I'm in favor of gradle.

**Comment by cblanto7** [comment]
#31

**Comment by cblanto7** [comment]
I believe we are moving foward with Gradle so I am closing this one
